### ISSUE TITLE
wbp has no method requireappfile

### ISSUE THREAD

**Issue by okwme** [openhoat/roulettejs#1]
i get this error when i try to run the app.
i'm pretty new to node and din't get any results from googling it..
have any idea why this happens?

../app.js:2
  , config = wbp.requireAppFile('config.js');
                 ^
TypeError: Object #<Object> has no method 'requireAppFile'

**Comment by openhoat** [comment]
It was a problem with dependency version, I've just pushed a patch, the 0.1.2 version should be ok.
Tell me if not :-)

**Comment by okwme** [comment]
thanks the app is running now!
but i'm not getting anything when i visit via browser with port 3005.
i've tried using the domain and the ip address of my server plus :3005 but no luck.
how do i access it?

**Comment by openhoat** [comment]
Did you try http://localhost:3005/ ?
You should get the main and unique html page of the app.

**Comment by okwme** [comment]
thanks for being so patient with me.
how do you access if it's running on a remote server though?

**Comment by openhoat** [comment]
Hi,

I have updated the app and fixed it, it's deployed on a server (see readme).
It should be ok now.
To use it on a server, simply modify the config/default.js to match your settings : 
for example add : { ... hostname: 'my.server.com', listenPort:80, ... }
It also works with unix sockets (that's what I'm using behind a nginx front on my server)

**Comment by okwme** [comment]
you're amazing thank you so much!
